apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: staging-api

namePrefix: staging-

commonLabels:
  app: staging-api-store

replicas:
  - name: staging-api-deployment
    count: 1