apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-test2
spec:
  destination:
    namespace: dev-api
    server: 'https://kubernetes.default.svc'
  source:
    path: environmets/dev
    repoURL: 'https://github.com/bartodes/k8s-devops-bootcamp.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    # automated:
    #   prune: true
    #   selfHeal: true