apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: api-store
  template:
    metadata:
      labels:
        app: api-store
    spec:
      containers:
      - name: api-store
        image: kustomize_image
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
spec:
  type: LoadBalancer
  selector:
    app: api-store
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30000