apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-api-store
  namespace: argocd
spec:
  project: default
  source:
    repoURL:  https://github.com/bartodes/kubernetes-devops-bootcamp.git
    targetRevision: HEAD
    path: base/
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-app
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
