apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: dev-api

namePrefix: dev-

commonLabels:
  app: dev-api-store

replicas:
  - name: dev-api-deployment
    count: 1