apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: dev-api

namePrefix: dev-

replicas:
  - name: dev-api-deployment
    count: 1

images:
  - name: kustomize_image
    newName: bartodes/api-store:0.0.27
